#!/usr/bin/python
# -*- coding: utf-8 -*-

# Essa classe contem a lista de nomes que compoem o Bingo

class NameListClass():
    def __init__(self):
        self._list = [
            'AMOR',
            'ALMOFADA DE AMAMENTAÇÃO',
            'ANDADOR',
            'ALGODÃO',
            'ALCOOL GEL',
            'ASPIRADOR NASAL',
            'BANHEIRA',
            'BABADOR',
            'BABÁ ELETRÔNICA',
            'BEBÊ CONFORTO',
            'BODY',
            'BOMBA TIRA LEITE',
            'CANGURU',
            'CAPA PARA CARRINHO',
            'BERÇO',
            'CARINHO',
            'CARRINHO',
            'CHUQUINHA',
            'COLHER DOSADORA',
            'BRINQUEDOS DE BANHO',
            'CULOTES',
            'CADEIRA ALIMENTAÇÃO',
            'CADEIRINHA VIBRATÓRIA',
            'COPO DE TRANSIÇÃO',
            'COBERTOR',
            'CONTA GOTAS',
            'DEDICAÇÃO',
            'ESTERILIZADOR',
            'ESCOVA PARA MAMADEIRA',
            'FRALDAS RN',
            'FRALDAS P',
            'FRALDAS M',
            'FRALDAS XXG',
            'FRALDA DE BOCA',
            'FRALDA DE PANO',
            'KIT HIGIENE',
            'KIT ESCOVA E PENTE',
            'LENÇO UMEDECIDO',
            'LUVA',
            'MAMÃE',
            'MAMADEIRA',
            'MANTA',
            'MOISES',
            'MATERNIDADE',
            'MASSAGEADOR DE GENGIVA',
            'MORDEDOR',
            'MOSQUETEIRO',
            'MOBILE',
            'PAPAI',
            'PAPINHA',
            'POMADA',
            'PROTETOR DE BERÇO',
            'POLTRONA DE AMAMENTAÇÃO',
            'PINÇA HIGIÊNICA',
            'POSICIONADOR PARA DORMIR',
            'PORTA CHUPETA',
            'ROUPA DE CAMA',
            'SLING',
            'SABONETE',
            'SABEDORIA',
            'SAPATINHO',
            'TOALHA FRALDA',
            'TAPETE INTERATIVO',
            'TERMOMÊTRO DE BANHEIRA',
            'TERMÔMETRO',
            'TIP TOP',
            'TITIA',
            'TROCADOR',
            'TALCO',
            'TRAVESSEIRO',
            'VOVÔ',
            'VOVÓ',
            'FRALDAS G',
            'TOUCA',
            'CUEIRO',
            'PRENDEDOR DE CHUPETA',
            'COTONETE',
            'CHUPETA',
            'SAÍDA MATERNIDADE',
            'ALINE',
            'FELIPE',
            'ORIENTAÇÃO',
            'EDUCAÇÃO',
            'FAMÍLIA',
            'CUIDADO',
            'BEBÊ',
            'BEM VINDA',
            'FRALDAS',
            'FILHA',
            'IRMÃO',
            'IRMÃ',
            'GÊMEOS',
            'LACINHO',
            'VESTIDO',
            'SAIA',
            'ASSADURA',
            'BOLSA',
            'DENTE',
            'CASAQUINHO'
        ]

    # metodo para obter o tamanho da lista
    def _GetListSize(self):
        return len(self._list)

    # metodo para obter a lista
    def _GetList(self):
        return self._list

